language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: a-simple-pipeline
  skip_cleanup: true
  acl: public_read
  on:
    all_branches: true