language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn sync

services:
  - docker

deploy:
  provider: s3
  access_key_id: "AKIAJ6OL275ZVCDLQU7Q"
  secret_access_key: "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"
  bucket: "a-simple-pipeline"